from __future__ import annotations

import argparse
import os
import shutil
from datetime import datetime
from pathlib import Path

import sys

# Allow running as `python scripts/mt5_cleanup.py` without installing the repo as a package.
REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from engine.terminals import TerminalRegistry


def _rm(path: Path) -> None:
    if not path.exists():
        return
    if path.is_dir():
        shutil.rmtree(path)
    else:
        path.unlink()


def _is_keep_file(path: Path, keep_stems: set[str]) -> bool:
    if not path.is_file():
        return False
    if path.suffix.lower() not in {".mq5", ".ex5"}:
        return False
    return path.stem in keep_stems


def _is_keep_core_only(path: Path, keep_stems: set[str]) -> bool:
    if not path.is_file():
        return False
    name = path.name
    for stem in keep_stems:
        if name == f"{stem}.mq5" or name == f"{stem}.ex5":
            return True
    return False


def main() -> int:
    ap = argparse.ArgumentParser(description="Clean MT5 Expert Advisors and Strategy Tester reports.")
    ap.add_argument("--terminal", default=None, help="Terminal name from terminals.json (default: active)")
    ap.add_argument("--keep-ea", default="RSI_Divergence_Pro", help="EA stem to keep (no extension)")
    ap.add_argument(
        "--keep-core-only",
        action="store_true",
        help="Keep only <EA>.mq5 and <EA>.ex5; archive/remove all other files in Experts root",
    )
    ap.add_argument("--archive", action="store_true", help="Move removed files into an archive folder")
    ap.add_argument("--reports-all", action="store_true", help="Delete ALL *.htm* and *.xml in terminal data_path root")
    ap.add_argument("--yes", action="store_true", help="Actually perform actions")
    args = ap.parse_args()

    registry = TerminalRegistry()
    if args.terminal:
        registry.set_active(args.terminal)
    terminal = registry.get_terminal()

    data_path = Path(terminal["data_path"])
    experts_dir = data_path / "MQL5" / "Experts"
    if not experts_dir.exists():
        raise SystemExit(f"Experts dir not found: {experts_dir}")

    keep_stems = {str(args.keep_ea).strip()}
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    archive_dir = data_path / f"ea_stress_cleanup_{stamp}"

    if args.keep_core_only:
        expert_root_files = sorted([p for p in experts_dir.iterdir() if p.is_file()])
        to_remove = [p for p in expert_root_files if not _is_keep_core_only(p, keep_stems)]
    else:
        ea_files = sorted([p for p in experts_dir.iterdir() if p.is_file() and p.suffix.lower() in {".mq5", ".ex5"}])
        to_remove = [p for p in ea_files if not _is_keep_file(p, keep_stems)]

    # Reports: MT5 writes reports in terminal data_path root.
    report_candidates = []
    if args.reports_all:
        report_candidates.extend(sorted(data_path.glob("*.htm*")))
        report_candidates.extend(sorted(data_path.glob("*.xml")))
    else:
        # Safer default: only remove reports that look like they were generated by this system.
        prefixes = ("RSI_", "London_", "Compression_", "Disequilibrium_", "EAStress", "workflow_", "boards", "leaderboard")
        for p in sorted(data_path.glob("*.htm*")) + sorted(data_path.glob("*.xml")):
            if p.name.startswith(prefixes):
                report_candidates.append(p)

    print("Planned MT5 cleanup:")
    print(f"- Terminal: {terminal.get('name')}")
    print(f"- data_path: {data_path}")
    print(f"- experts_dir: {experts_dir}")
    print(f"- Keeping EA stem(s): {', '.join(sorted(keep_stems))}")
    print(f"- EA files to remove: {len(to_remove)}")
    for p in to_remove[:50]:
        print(f"  - {p}")
    if len(to_remove) > 50:
        print("  - ...")
    print(f"- Report files to remove: {len(report_candidates)}")
    for p in report_candidates[:50]:
        print(f"  - {p}")
    if len(report_candidates) > 50:
        print("  - ...")

    if not args.yes:
        print("\nDry-run only. Re-run with --yes to perform.")
        return 0

    if args.archive:
        archive_dir.mkdir(parents=True, exist_ok=True)
        ea_dest = archive_dir / "Experts"
        rep_dest = archive_dir / "Reports"
        ea_dest.mkdir(parents=True, exist_ok=True)
        rep_dest.mkdir(parents=True, exist_ok=True)
        for p in to_remove:
            try:
                shutil.move(str(p), str(ea_dest / p.name))
            except Exception:
                pass
        for p in report_candidates:
            try:
                shutil.move(str(p), str(rep_dest / p.name))
            except Exception:
                pass
        print(f"Archived to: {archive_dir}")
        return 0

    for p in to_remove:
        _rm(p)
    for p in report_candidates:
        _rm(p)

    # Also prune any empty archive folders we created earlier.
    try:
        for p in experts_dir.iterdir():
            if p.is_dir() and p.name.lower().startswith("ea_stress"):
                try:
                    os.rmdir(p)
                except Exception:
                    pass
    except Exception:
        pass

    print("MT5 cleanup complete.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
